# Generated by Django 4.2.7 on 2023-12-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('income', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('income', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sold', models.DateField()),
                ('num', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('prepayment', models.BooleanField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_sold', to='app.broker')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('unit', models.CharField(max_length=100)),
                ('shelf_life', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductByCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_produced', to='app.company')),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_in', to='app.consignment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_by', to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='broker',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to='app.brokercompany'),
        ),
    ]
